version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, rust]

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    labels: [dependencies, javascript]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, github-actions]
